### ISSUE TITLE
NoSuchElementException: Pool exhausted when starting app

### ISSUE THREAD

**Issue by hepin1989** [lettuce-io/lettuce-core#1423]
#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
Caused by: java.util.NoSuchElementException: Pool exhausted
  at io.lettuce.core.support.BoundedAsyncPool.acquire()(Unknown Source)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
 client = RedisClient.create();
        client.setOptions(
            ClientOptions.builder()
                .autoReconnect(true)
                .cancelCommandsOnReconnectFailure(true)
                .requestQueueSize(1024 * Runtime.getRuntime().availableProcessors())
                .build());
        final RedisURI redisURI = RedisURI.builder()
            .withHost(redisAddr)
            .withPort(6379) //默认值
            .withPassword(redisPassword)
            .build();

        pool = AsyncConnectionPoolSupport.createBoundedObjectPool(
            () -> client.connectAsync(StringCodec.UTF8, redisURI),
            //默认8个连接
            //refs:https://github.com/lettuce-io/lettuce-core/issues/1363
            BoundedPoolConfig.builder()
                .maxTotal(Runtime.getRuntime().availableProcessors() * 2)
                .minIdle(Runtime.getRuntime().availableProcessors())
                .build());
        final String pong = pool.acquire().get().sync().ping();
```

</details>

#### Environment

        <lettuce.version>5.3.4.RELEASE</lettuce.version>

**Comment by hepin1989** [comment]
Isn't this fixed in refs:https://github.com/lettuce-io/lettuce-core/issues/1363
?

**Comment by mp911de** [comment]
I also think that's a duplicate of #1363. By awaiting initialization via `BoundedAsyncPool.create(…)`, the pool should no longer throw exceptions. I also think we should investigate whether we can detect in-flight creations and attach the acquisition to the asynchronous pool warming. Can you upgrade to 5.3.4 and retest whether the issue persists?

**Comment by hepin1989** [comment]
@mp911de Yes, I was using the 5.3.4, so I was wondering...
![image](https://user-images.githubusercontent.com/501740/93805633-9557f280-fc7a-11ea-935f-c97ec1a73009.png)
I am currently using lettuce to connect to aliyun's redis. I will try to dig this out.

**Comment by mp911de** [comment]
#1363 introduced two new methods `BoundedAsyncPool.create(…)` and `AsyncConnectionPoolSupport.createBoundedObjectPoolAsync(…)` that return `CompletionStage<Pool>`. We didn't want to introduce blocking behavior so adding new methods was the only option to allow for synchronization.

**Comment by hepin1989** [comment]
@mp911de I will read through the PR and feedback.

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/94430561-b4004100-01c6-11eb-9245-f4d6a6f2ed14.png)
@mp911de It's still there after I updated the code

**Comment by mp911de** [comment]
Thanks for report. We need to check why this is.

**Comment by hepin1989** [comment]
@mp911de After I set the maxTotal to match the concurrent acquire threads number, it disappears.

**Comment by mp911de** [comment]
Providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem would be helpful. Since I don't have any insight into what the application is doing it's not possible to further diagnose the issue.

**Comment by hepin1989** [comment]
@mp911de I will close this one, cause it's turn out to be an underside issue. thanks.

**Comment by vsharathis** [comment]
@He-Pin , I encountered same issue, can you please share the code snippet to mitigate the issue ?
 Timeout occurred while populating hgetall : **java.util.concurrent.CompletionException: java.util.NoSuchElementException: Pool exhausted**

**Comment by Brico87** [comment]
Hi @vsharathis, I do not know if this is the correct way of doing stuff (@mp911de could validate) but to avoid that error, it seems you need to prepare your async pool like that:
```
public AsyncPool<StatefulRedisConnection<String, String>> createAsyncConnectionPool(RedisURI redisURI, int connectionPoolSize) {
        var boundedPoolConfig = BoundedPoolConfig.builder()
                .minIdle(connectionPoolSize)
                .maxTotal(connectionPoolSize)
                .build();
        return AsyncConnectionPoolSupport.createBoundedObjectPool(() -> redisClient.connectAsync(StringCodec.UTF8, redisURI), boundedPoolConfig);
    }
```

By forcing the pool to initialize all connections in IDLE mode, then no "pool exhauted" error :)

Cheers !

**Comment by vsharathis** [comment]
@Brico87 , Thanks for the comment, what is the best "connectionPoolSize" to manage, is it based the number of transactions per second or do need to follow some formula to define it. Please do clarify , thanks

**Comment by Brico87** [comment]
I think I let that to @mp911de answer that but I put a random 10 :)

**Comment by vsharathis** [comment]
After setting pool size to 1000 and executor thread to 1000 still we encountering pool size exhaust exception

**Comment by vsharathis** [comment]
@Brico87 , yes ASYC is must

**Comment by ovk-hbomax** [comment]
@vsharathis , can you elaborate the need of async here?

**Comment by He-Pin** [comment]
IIRC, I was increase the max pooled number, I have no access to the codes now. @vsharathis ，sorry。

**Comment by demkom58** [comment]
Why would it even throw an exception like this instead of returning the connection later when it's available?
